name: tomcat-live-recon
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - cmake>=3.16
  - boost=1.80.0
  - spdlog=1.9.2
  - cppzmq=4.8.1
  - eigen=3.4.0
  - fftw=3.3.10
  - tbb-devel=2021.7
  - nlohmann_json=3.11.2
  - libastra=2.1.0