site_name: RECASTX
nav:
  - Introduction: index.md
  - Installation: installation.md
  - User Guide:
      - Getting started: user_guide/usage.md
      - GUI: user_guide/gui.md
      - Data protocol: user_guide/data_protocol.md
      - Performance consideration: user_guide/performance_consideration.md
  - Tutorial:
      - Plastic beads (3D): tutorial/plastic_beads.md
      - Dynamic tomography (4D): tutorial/dynamic_tomography.md
  - FAQ: faq.md

theme:
  name: material
  features:
    - content.code.copy
    - navigation.expand
  icon:
    admonition:
      <type>: material/alert-circle

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
