site_name: RECASTX

nav:
  - Home: index.md
  - Getting started:
      - Installation: installation.md
      - Starting pipeline: run.md
  - Tutorial:
      - Plastic beads (3D): tutorial/plastic_beads.md
      - Foam (4D): tutorial/foam.md
  - User guide:
      - GUI: gui.md
      - Data protocol: data_protocol.md
      - Performance consideration: performance_consideration.md
  - FAQ: faq.md

theme:
  name: material
  features:
    - content.code.copy
    - content.action.view
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - toc.follow
    - toc.integrate
  icon:
    admonition:
      <type>: material/alert-circle

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/zhujun98
    - icon: fontawesome/solid/paper-plane
      link: mailto:<zhujun981661@gmail.com>

copyright: Copyright (c) 2022- Paul Scherrer Institut (Jun Zhu)